# Generated by Django 5.0.4 on 2024-05-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imageUrl',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
